# Generated by Django 2.0.5 on 2018-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raportinlinks',
            name='client',
        ),
        migrations.DeleteModel(
            name='RaportInlinks',
        ),
    ]
