# Generated by Django 2.0.5 on 2018-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20180829_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportInlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crawled', models.DateField()),
                ('url_info', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('encoding', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('title_len', models.IntegerField()),
                ('title_len_pix', models.IntegerField()),
                ('description', models.TextField()),
                ('desc_len', models.IntegerField()),
                ('desc_len_pix', models.IntegerField()),
                ('h1_1', models.CharField(max_length=255)),
                ('h1_1_len', models.IntegerField()),
                ('h1_2', models.CharField(max_length=255)),
                ('h1_2_len', models.IntegerField()),
                ('h2_1', models.CharField(max_length=255)),
                ('h2_1_len', models.IntegerField()),
                ('h2_2', models.CharField(max_length=255)),
                ('h2_2_len', models.IntegerField()),
                ('meta_robots', models.CharField(max_length=255)),
                ('noindex', models.IntegerField()),
                ('nofollow', models.IntegerField()),
                ('meta_refresh', models.CharField(max_length=255)),
                ('canonical', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('text_ratio', models.IntegerField()),
                ('crawl_depth', models.IntegerField()),
                ('inlinks', models.IntegerField()),
                ('unique_inlinks', models.IntegerField()),
                ('percent_total', models.IntegerField()),
                ('outlinks', models.IntegerField()),
                ('unique_outlinks', models.IntegerField()),
                ('external_outlinks', models.IntegerField()),
                ('unique_external_outlinks', models.IntegerField()),
                ('response_time', models.IntegerField()),
                ('last_modified', models.CharField(max_length=255)),
                ('redirect_URI', models.CharField(max_length=255)),
                ('redirect_type', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete='Cascade', to='tool.Client')),
            ],
        ),
    ]
