# Generated by Django 2.0.5 on 2018-08-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_raportinlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaportInlinks',
            new_name='RaportInlink',
        ),
    ]
