# Generated by Django 2.0.5 on 2018-08-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20180829_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raportinlink',
            old_name='encoding',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='raportinlink',
            name='resource_type',
        ),
    ]
