# Generated by Django 2.0.5 on 2018-07-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20180719_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportScreamingtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crawled', models.DateField()),
                ('total_url_encountered', models.IntegerField()),
                ('total_url_crawled', models.IntegerField()),
                ('client', models.ForeignKey(on_delete='Cascade', to='tool.Client')),
            ],
        ),
    ]
