# Generated by Django 2.0.5 on 2018-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_auto_20180829_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportinlink',
            name='status',
            field=models.CharField(default='OK', max_length=255),
            preserve_default=False,
        ),
    ]
